Revert "Watchlist/Favorite (#15)" (#17)
This reverts commit 4bf5db97877a5d489fefd83f413cfd5bcd9040fa.

src/routes/circles.ts(36,17): error TS2339: Property 'moderators' does not exist on type 'FlattenMaps<{ name: string; visibility: "private" | "public"; createdBy: ObjectId; members: ObjectId[]; description?: string | null; inviteCode?: string | null; createdAt: NativeDate; updatedAt: NativeDate; }> & { ...; } & { ...; }'.
src/routes/circles.ts(36,34): error TS7006: Parameter 'mod' implicitly has an 'any' type.
src/routes/circles.ts(520,25): error TS2339: Property 'moderators' does not exist on type 'FlattenMaps<{ name: string; visibility: "private" | "public"; createdBy: ObjectId; members: ObjectId[]; description?: string | null; inviteCode?: string | null; createdAt: NativeDate; updatedAt: NativeDate; }> & { ...; } & { ...; }'.
src/routes/circles.ts(520,42): error TS7006: Parameter 'mod' implicitly has an 'any' type.
src/routes/circles.ts(552,36): error TS2339: Property 'moderators' does not exist on type 'Document<unknown, {}, { name: string; visibility: "private" | "public"; createdBy: ObjectId; members: ObjectId[]; description?: string | null; inviteCode?: string | null; } & DefaultTimestampProps, {}, { ...; }> & { ...; } & DefaultTimestampProps & { ...; } & { ...; }'.
src/routes/circles.ts(552,53): error TS7006: Parameter 'mod' implicitly has an 'any' type.
src/routes/circles.ts(596,14): error TS2339: Property 'moderators' does not exist on type 'Document<unknown, {}, { name: string; visibility: "private" | "public"; createdBy: ObjectId; members: ObjectId[]; description?: string | null; inviteCode?: string | null; } & DefaultTimestampProps, {}, { ...; }> & { ...; } & DefaultTimestampProps & { ...; } & { ...; }'.
src/routes/circles.ts(596,31): error TS7006: Parameter 'mod' implicitly has an 'any' type.
==> Build failed